spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm

server:
  port: 8082
